import './About.css';

function About() {
  return (
    <div className="about-container">
      <body className="about-body">
        <h1 className="about-header">About The Elder Scrolls</h1>
        <p className="about-paragraphs">The Elder Scrolls franchise is a highly influential and beloved series of action role-playing video games (RPGs) developed by Bethesda Game Studios. First released in 1994, the series is set in a rich and immersive high-fantasy universe that features an expansive world, deep lore, and a strong emphasis on player freedom. Unlike many RPGs that restrict players to a linear storyline or confined gameplay mechanics, the Elder Scrolls games are known for their open-world design, allowing players to explore vast landscapes, choose their own path, and engage with a multitude of side quests, characters, and systems.</p>
        <p className="about-paragraphs">The first game in the series, The Elder Scrolls: Arena, was released in 1994. Arena introduced the core concepts of the series, including first-person combat, a vast open world, and a focus on player freedom. Though it was initially planned to be a gladiatorial combat game, it evolved into a full-fledged RPG with a sprawling world for players to explore. The critical reception to Arena was mixed due to its technical challenges, but it laid the groundwork for the series' future success.</p>
        <p className="about-paragraphs">The sequel, The Elder Scrolls II: Daggerfall (1996), expanded on the ideas introduced in Arena. Daggerfall is most notable for its enormous game world, one of the largest in video game history, spanning thousands of towns and dungeons across a procedurally generated world. The game also introduced more complex role-playing mechanics, such as guilds, political factions, and the ability for players to make impactful choices. Daggerfall was also the first game to introduce the province of Tamriel, which would become the setting for future titles in the series.</p>
        <p className="about-paragraphs">One of the most critically acclaimed entries in the franchise is The Elder Scrolls III: Morrowind (2002). Morrowind introduced players to the exotic island of Vvardenfell, where they could explore a rich and detailed world filled with unique architecture, political intrigue, and alien-like landscapes. The game also featured a fully hand-crafted world, in contrast to the procedurally generated environments of the earlier games. Morrowind's complex story, freedom of character development, and modding support made it a landmark in the series.</p>
        <p className="about-paragraphs">The Elder Scrolls IV: Oblivion (2006) marked another leap forward in terms of graphics, world design, and accessibility. Set in the province of Cyrodiil, Oblivion featured a more traditional medieval fantasy setting compared to the alien landscapes of Morrowind. The game introduced a new AI system called Radiant AI, which gave NPCs more dynamic behaviors, and it also featured the Oblivion Gates, which were portals to a demonic realm that players could close throughout the game. Oblivion was praised for its detailed graphics and open-world gameplay but faced some criticism for its simplification of certain RPG elements.</p>
        <p className="about-paragraphs">The series reached new heights of popularity with The Elder Scrolls V: Skyrim (2011). Skyrim is set in the frozen northern province of Tamriel and allows players to assume the role of the Dragonborn, a hero with the power to speak in the language of dragons. The game’s world was filled with diverse environments, including snowy mountains, dense forests, and ancient ruins. Skyrim introduced dual-wielding combat and dragon shouts, adding fresh gameplay mechanics. Its open-world design, massive modding community, and accessibility helped it become one of the most successful RPGs of all time, reaching both dedicated fans and casual players.</p>
        <p className="about-paragraphs">One of the notable aspects of the Elder Scrolls series is its focus on deep and intricate lore. Each game is set in different parts of Tamriel, a continent filled with various cultures, races, and political factions. Players encounter humans, elves, orcs, and beast races like the feline Khajiit or the reptilian Argonians. The games feature complex histories, mythologies, and religious systems, much of which players can explore through in-game books, quests, and conversations with NPCs. This lore serves as a backdrop to the main stories but also adds layers of immersion and depth to the game world.</p>
        <p className="about-paragraphs">The franchise also has a multiplayer spin-off, The Elder Scrolls Online (2014), which is set in the same universe but allows players to explore Tamriel with others in a massive online environment. While the core games are known for their single-player focus, The Elder Scrolls Online offers a different experience, allowing players to band together to tackle quests, dungeons, and large-scale player-vs-player combat in the form of faction-based warfare.</p>
        <p className="about-paragraphs">A significant part of the Elder Scrolls franchise’s appeal is its support for mods. Since Morrowind, the games have offered players tools to create their own content, leading to a thriving modding community. These mods range from small tweaks to the game’s interface or mechanics to total overhauls that introduce new quests, lands, or features. Skyrim, in particular, has one of the most active modding communities in gaming, with thousands of mods that extend the game’s lifespan well beyond its initial release.</p>
        <p className="about-paragraphs">Looking forward, The Elder Scrolls VI is currently in development, with fans eagerly awaiting more details about the game. The franchise's long history, deep lore, and focus on player freedom have made it a defining series in the RPG genre, and it continues to influence other open-world games across the industry. While Bethesda has been focused on other projects, such as Starfield, the anticipation for the next Elder Scrolls game remains high.</p>
        <p className="about-paragraphs">The Elder Scrolls series stands as a landmark in video game history, known for its massive worlds, rich lore, and emphasis on player choice. Its blend of freedom, deep storytelling, and immersive environments has left a lasting legacy, making it one of the most cherished and successful RPG franchises in gaming.</p>
      </body>
    </div>
  );
}

export default About;
